const images = {
  background1: require('./img/background.png'),
  background2: require('./img/background2.png'),
  logo: require('./img/Logo.png'),
  guide1: require('./img/guide1.png'),
  guide2: require('./img/guide2.png'),
  guide3: require('./img/guide3.png'),
  guide4: require('./img/guide4.png'),
  MyInfo: require('./img/MyInfo.png'),
  MyInfoActive: require('./img/MyInfoActive.png'),
  Academy: require('./img/Academy.png'),
  AcademyActive: require('./img/AcademyActive.png'),
  Message: require('./img/Message.png'),
  MessageActive: require('./img/MessageActive.png'),
  Achievement: require('./img/Achievement.png'),
  AchievementActive: require('./img/AchievementActive.png'),
  Credits: require('./img/Credits.png'),
  CreditsActive: require('./img/CreditsActive.png'),
  Setting: require('./img/Setting.png'),
  school: require('./img/school.png'),
  school1: require('./img/school1.png'),
  rewards: require('./img/rewards.png'),
  diamond: require('./img/diamond.png'),
  Credit: require('./img/Credit.png'),
  Collection: require('./img/Collection.png'),
  Icon1: require('./img/Icon1.png'),
  score1: require('./img/score1.png'),
  Lion: require('./img/Lion.png'),
  Verification1: require('./img/Verification1.png'),
  Verification2: require('./img/Verification2.png'),
  Group: require('./img/Group.png'),
  Frame23: require('./img/Frame23.png'),
  logo1: require('./img/logo1.png'),
  img: require('./img/img.png'),
  Vector: require('./img/Vector.png'),
  item1: require('./img/item1.png'),
  item2: require('./img/item2.png'),
  item3: require('./img/item3.png'),
  item4: require('./img/item4.png'),
  feedback: require('./img/feedback.png')
}

export default images;